tools:
    php_mess_detector: true
    php_code_sniffer: true
    php_code_coverage: true
    php_pdepend: true
    php_loc:
        enabled: true
        excluded_dirs: [vendor, tests]
checks:
    php:
        code_rating: true
        duplication: true
filter:
    excluded_paths:
        - 'tests/*'
build:
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=my-coverage-file'
                coverage:
                    file: 'my-coverage-file'
                    format: 'php-clover'
